
# 数据源配置
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/springbootdemo?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: root
    password: root

# mybatis-plus配置
#mybatis-plus:
#  mapper-localtions: classpath:mapper/*.xml